
package vistas;

import javax.swing.JOptionPane;
import modelo.Alumno;
import modelo.Docente;
import dao.AlumnoIMPDAO;

public class VtnDocentes extends javax.swing.JFrame {
    VtnPrincipal vtnPrincipal = null;
    Alumno objAl = null;
    Docente objDoc = null;
    AlumnoIMPDAO bd = new AlumnoIMPDAO();
    

    public VtnDocentes(VtnPrincipal vtnPrincipal,
                       Alumno objAl,
                       Docente objDoc) {
        this.vtnPrincipal = vtnPrincipal;
        this.objAl = objAl;
        this.objDoc = objDoc;
        
        initComponents();
        ocultarComponentes();
    }
    
    public VtnDocentes() {
        initComponents();
        ocultarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        tbpDocente = new javax.swing.JTabbedPane();
        pnlRegistrar = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblHoras = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        lblPago = new javax.swing.JLabel();
        txtPago = new javax.swing.JTextField();
        pnlEvaluar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        txtMate = new javax.swing.JTextField();
        lblMate = new javax.swing.JLabel();
        lblFisica = new javax.swing.JLabel();
        txtFisica = new javax.swing.JTextField();
        lblProgra = new javax.swing.JLabel();
        txtProgra = new javax.swing.JTextField();
        btnEvaluar = new javax.swing.JButton();
        pnlEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        lbleliminar = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Cantarell", 3, 26)); // NOI18N
        lblTitulo.setText("Docentes");

        lblNombre.setText("Nombre :");

        lblEdad.setText("Edad :");

        txtEdad.setColumns(3);

        lblEmail.setText("Email :");

        lblCodigo.setText("Codigo :");

        txtCodigo.setColumns(5);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblHoras.setText("Horas:");

        txtHoras.setColumns(3);

        lblPago.setText("Pago:");

        txtPago.setColumns(5);

        javax.swing.GroupLayout pnlRegistrarLayout = new javax.swing.GroupLayout(pnlRegistrar);
        pnlRegistrar.setLayout(pnlRegistrarLayout);
        pnlRegistrarLayout.setHorizontalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPago)
                    .addComponent(lblHoras))
                .addGap(27, 27, 27)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(24, 24, 24))
            .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRegistrarLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCodigo)
                        .addComponent(lblEmail)
                        .addComponent(lblEdad)
                        .addComponent(lblNombre))
                    .addGap(18, 18, 18)
                    .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(143, Short.MAX_VALUE)))
        );
        pnlRegistrarLayout.setVerticalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrarLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(30, 30, 30)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPago)
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRegistrarLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombre)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEdad)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        tbpDocente.addTab("Registrar", pnlRegistrar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscar.setColumns(5);

        txtMate.setColumns(3);

        lblMate.setText("Matematicas");

        lblFisica.setText("Fisica");

        txtFisica.setColumns(3);

        lblProgra.setText("Programación");

        txtProgra.setColumns(3);

        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEvaluarLayout = new javax.swing.GroupLayout(pnlEvaluar);
        pnlEvaluar.setLayout(pnlEvaluarLayout);
        pnlEvaluarLayout.setHorizontalGroup(
            pnlEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvaluarLayout.createSequentialGroup()
                .addGroup(pnlEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvaluarLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnBuscar)
                        .addGap(41, 41, 41)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEvaluarLayout.createSequentialGroup()
                        .addGroup(pnlEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEvaluarLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(txtMate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvaluarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblMate)
                                .addGap(31, 31, 31)))
                        .addGroup(pnlEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEvaluarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblFisica))
                            .addComponent(txtFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEvaluarLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblProgra))
                            .addGroup(pnlEvaluarLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(txtProgra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlEvaluarLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnEvaluar)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlEvaluarLayout.setVerticalGroup(
            pnlEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvaluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(pnlEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProgra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMate)
                    .addComponent(lblFisica)
                    .addComponent(lblProgra))
                .addGap(18, 18, 18)
                .addComponent(btnEvaluar)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        tbpDocente.addTab("Evaluar", pnlEvaluar);

        txtEliminar.setColumns(5);

        btnEliminar.setText("Eliminar Alumno");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lbleliminar.setText("Para eliminar un alumno es necesario ingresar su código");

        javax.swing.GroupLayout pnlEliminarLayout = new javax.swing.GroupLayout(pnlEliminar);
        pnlEliminar.setLayout(pnlEliminarLayout);
        pnlEliminarLayout.setHorizontalGroup(
            pnlEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarLayout.createSequentialGroup()
                .addComponent(lbleliminar)
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(pnlEliminarLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEliminarLayout.setVerticalGroup(
            pnlEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(lbleliminar)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        tbpDocente.addTab("Eliminar", pnlEliminar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(tbpDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(40, 40, 40)
                .addComponent(tbpDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       vtnPrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
           
        objDoc.setNombre(txtNombre.getText());
        objDoc.setEdad(Integer.parseInt(txtEdad.getText()));
        objDoc.setEmail(txtEmail.getText());
        objDoc.setCodigo(txtCodigo.getText());
        objDoc.setCantHoras(Integer.parseInt(txtHoras.getText()));
        objDoc.setPagoHora(Double.parseDouble(txtPago.getText()));
      
        JOptionPane.showMessageDialog(this, "Docente guardado correctamente");
        
        limpiarCajas();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String buscado = txtBuscar.getText();
        
        bd.abrirConexion();
        objAl = bd.consultarAlumno(buscado);
        bd.cerrarConexion();
        
        if(objAl != null) {
            JOptionPane.showMessageDialog(this, "Alumno encontrado, lo puedes evaluar");
            mostrarComponentes();
        }else{
           JOptionPane.showMessageDialog(this, "Alumno No existe"); 
           ocultarComponentes();
        }
        limpiarCajas();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed
        
        objDoc.evaluarAlumno(objAl,
                Double.parseDouble(txtMate.getText()),
                Double.parseDouble(txtFisica.getText()),
                Double.parseDouble(txtProgra.getText()) );
        
        bd.abrirConexion();
        bd.actualizarAlumno(objAl);
        bd.cerrarConexion();
        
        JOptionPane.showMessageDialog(this, "Alumno Evaluado");
        ocultarComponentes();
        limpiarCajas();
    }//GEN-LAST:event_btnEvaluarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String eliminado = txtEliminar.getText();
        bd.abrirConexion();
        objAl = bd.consultarAlumno(eliminado);
        
        if(objAl != null){
            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Deseas eliminar al alumno :" + objAl.getNombre());
            
            if(opcion == 0) {
                bd.eliminarAlumno(eliminado);
                JOptionPane.showMessageDialog(this,
                        "Alumno Eliminado de la BD");
            }else{
                JOptionPane.showMessageDialog(this,
                        "El Alumno sigue activo en la BD");
            }
        }else{
            JOptionPane.showMessageDialog(this,
                    "No existe el Alumno con ese código en la BD");
        }
        bd.cerrarConexion();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    public void ocultarComponentes(){
        lblMate.setVisible(false);
        lblFisica.setVisible(false);
        lblProgra.setVisible(false);
        txtMate.setVisible(false);
        txtFisica.setVisible(false);
        txtProgra.setVisible(false);
        btnEvaluar.setVisible(false);
 
    }
    
    public void mostrarComponentes(){
        lblMate.setVisible(true);
        lblFisica.setVisible(true);
        lblProgra.setVisible(true);
        txtMate.setVisible(true);
        txtFisica.setVisible(true);
        txtProgra.setVisible(true);
        btnEvaluar.setVisible(true);
    }
    
    public void limpiarCajas(){
        txtNombre.setText("");
        txtEdad.setText("");
        txtEmail.setText("");
        txtCodigo.setText("");
        txtHoras.setText("");
        txtPago.setText("");
        txtMate.setText("");
        txtFisica.setText("");
        txtProgra.setText("");
        txtBuscar.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnDocentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFisica;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JLabel lblMate;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblProgra;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbleliminar;
    private javax.swing.JPanel pnlEliminar;
    private javax.swing.JPanel pnlEvaluar;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JTabbedPane tbpDocente;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFisica;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtMate;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtProgra;
    // End of variables declaration//GEN-END:variables
}
